name: Build Renpy Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      # 安装 JDK
      - name: Install Java toolchain
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      # 安装 Android 环境
      - name: Install Android toolchain
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"
      # 设置 Renpy 环境
      - name: Setup Ren'Py
        uses: remarkablegames/setup-renpy@v1
        with:
          cli-version: 8.5.2
          rapt: true
          launcher-name: renpy-launcher
      # 开始构建 Android
      - name: Run Build
        run: |
          renpy-launcher
          renpy-launcher android_build --destination ./build
      # 上传工件
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: ./build
